# Generated by Django 5.2.6 on 2026-01-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_center', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingSlot',
        ),
        migrations.DeleteModel(
            name='ChargingStations',
        ),
    ]
