# Generated by Django 5.2.6 on 2026-01-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charging_center', '0002_delete_chargingslot_delete_chargingstations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ev_station/')),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the station', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the station', max_digits=9)),
                ('working_hours', models.CharField(max_length=50)),
                ('connectors', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('ccs2', 'CCS2'), ('gbt', 'GB/T'), ('chademo', 'CHAdeMO')], max_length=100)),
                ('rate_per_slot', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChargingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='charging_center.chargingstations')),
            ],
        ),
    ]
