# Generated by Django 5.2.6 on 2026-01-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_center', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingSlot',
        ),
    ]
