# Generated by Django 5.2.6 on 2026-01-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_center', '0004_delete_chargingslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='charging_center.chargingstations')),
            ],
        ),
    ]
