# Generated by Django 5.2.6 on 2026-01-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_center', '0005_chargingslot'),
        ('user_app', '0021_delete_slotbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargingSlot',
        ),
        migrations.DeleteModel(
            name='ChargingStations',
        ),
    ]
