# Generated by Django 6.0 on 2025-12-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Centre',
        ),
    ]
