# Generated by Django 6.0 on 2025-12-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0002_delete_service_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_center_photos/')),
                ('working_hours', models.CharField(default='', max_length=55)),
                ('utype', models.CharField(default='service_centre', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
