# Generated by Django 6.0 on 2025-12-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registration_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
