# Generated by Django 6.0 on 2025-12-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_evservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVService',
        ),
    ]
