# Generated by Django 6.0 on 2025-12-23 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_products'),
        ('user_app', '0004_delete_evservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('software', 'Software Update'), ('charging', 'Charging Service'), ('battery', 'Battery Service'), ('water', 'Water Wash'), ('mechanical', 'Mechanical Service'), ('electrical', 'Electrical Service')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_services', to='service_app.service_centre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
