# Generated by Django 6.0 on 2026-01-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_evservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVService',
        ),
    ]
