# Generated by Django 6.0 on 2026-01-07 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_productorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
