# Generated by Django 6.0 on 2026-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], default='pending', max_length=20),
        ),
    ]
