# Generated by Django 6.0 on 2026-01-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_productorder_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
