# Generated by Django 6.0 on 2026-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_productorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='otp',
        ),
    ]
