# Generated by Django 5.2.6 on 2026-01-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_slotbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slotbooking',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
