# Generated by Django 5.2.6 on 2026-01-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_slotbooking_options_alter_slotbooking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotBooking',
        ),
    ]
