# Generated by Django 5.2.6 on 2026-01-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_slotbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotBooking',
        ),
    ]
