# Generated by Django 5.2.6 on 2026-01-24 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_center', '0007_initial'),
        ('user_app', '0023_delete_slotbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.BooleanField(default=False)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charging_center.chargingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
